MyBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('blog/', include('blog.urls')),
    path('', views.index, name='index'),
]

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [

    path('post/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('add/', views.PostCreate.as_view(), name='add'),
    path('update/<int:pk>/', views.PostUpdate.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDelete.as_view(), name='delete'),
    path('subscribe/<int:pk>/', views.subscribe, name='subscribe'),
    path('readed/<int:id>/', views.readed, name='readed'),
    path('', views.PostListView.as_view(), name='blog'),


]

blog/models.py
from django.contrib.auth.models import User
from django.core.mail import send_mass_mail
from django.db import models
from django.urls.base import reverse
from django.db.models.signals import post_save
from django.dispatch import receiver
from MyBlog import settings


class Blog(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    title = models.CharField(max_length=100, unique=True)
    subscribed = models.ManyToManyField(User, related_name='subscribed', blank=True)
    created = models.DateTimeField(db_index=True, auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Блог"
        verbose_name_plural = "Блоги"


class Post(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField('Заголовок', max_length=200)
    content = models.TextField('Текст')
    readed_user = models.ManyToManyField(User, blank=True)
    posted = models.DateTimeField(db_index=True, auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.id)])

    class Meta:
        ordering = ["-posted"]
        verbose_name_plural = 'Публикации'


@receiver(post_save, sender=Post)
def send_mail(sender, instance, **kwargs):
    post = instance
    users = Blog.objects.filter(subscribed__post=post)
    message = 'Новая публикация на сайте, перейти ' + str(settings.SITE_URL) + str(post.get_absolute_url())
    datatuple = (
        ('Новая публикация', message, 'from@mymail.com', users),
    )
    print(datatuple)
    send_mass_mail(datatuple, fail_silently=True)

blog/forms.py
from django.contrib.auth.models import User
from django.forms import Textarea

from .models import Post, Blog
from django import forms


class PostForm(forms.ModelForm):
    title = forms.CharField(label="Заголовок", widget=forms.TextInput(attrs={'size': 100}), )
    content = forms.Textarea()

    class Meta:
        model = Post
        fields = ('title', 'content')
        widgets = {
            'content': Textarea(attrs={'cols': 100, 'rows': 5}),
        }

    def __init__(self, *args, **kwargs):
        blog = kwargs.pop('blog', None)
        super(PostForm, self).__init__(*args, **kwargs)


class Blog1Form(forms.ModelForm):
    title = forms.CharField(label="Заголовок")

    class Meta:
        model = Blog
        fields = ('title',)


class UserForm(forms.ModelForm):
    subscribed = forms.ModelMultipleChoiceField(queryset=Blog.objects.all(), label='Доступные блоги',
                                                widget=forms.CheckboxSelectMultiple, required=False)

    class Meta:
        model = User
        fields = ('subscribed',)

blog/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView

from .forms import PostForm, UserForm
from .models import Post, Blog


@login_required
def index(request, **kwargs):
    posts = Post.objects.filter(blog__subscribed__username=request.user.username)
    blogs = Blog.objects.filter(subscribed__username=request.user.username)
    pages = 10
    paginator = Paginator(posts, pages)
    page = request.GET.get('page')
    news = paginator.get_page(page)

    return render(request, 'index.html', {'news': news, 'blogs': blogs})


def readed(request, id):
    user = request.user
    post = Post.objects.get(id=id)
    if (user not in post.readed_user.all()):
        post.readed_user.add(user)

    print()
    return redirect('index')


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post.html'


class PostCreate(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_add.html'

    def get_form_kwargs(self):
        kwargs = super(PostCreate, self).get_form_kwargs()
        blog = Blog.objects.get(owner=self.request.user)
        kwargs.update({'blog': blog})
        return kwargs

    def form_valid(self, form):
        form.instance.blog = Blog.objects.get(owner=self.request.user)
        return super(PostCreate, self).form_valid(form)


class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_update.html'


class PostDelete(LoginRequiredMixin, DeleteView):
    model = Post
    form_class = PostForm
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('blog:blog')

    def get_object(self, queryset=None):
        """ Hook to ensure object is owned by request.user. """
        obj = super(PostDelete, self).get_object()
        if not obj.blog.owner == self.request.user:
            raise Http404
        return obj


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'blog/main.html'
    paginate_by = 10

    def get_queryset(self):
        queryset = Post.objects.filter(blog__owner__username=self.request.user)

        return queryset


def subscribe(request, **kwargs):
    # current subscribe
    blogs = Blog.objects.filter(subscribed=request.user)

    # setting subscribe
    # select = Blog.objects.filter(subscribed=request.user).values_list('owner_id', flat=True)
    select = Blog.objects.filter(subscribed=request.user).prefetch_related('subscribed').values_list('subscribed__blog',
                                                                                                     flat=True)
    form = UserForm(initial={'subscribed': select})
    form.save(commit=False)
    user = request.user
    user.subscribed.clear()
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            for k, v in form.cleaned_data.items():
                for i in range(len(v)):
                    user.subscribed.add(v[i])
            return redirect('index')
        else:
            print(form.errors)

    return render(request, 'blog/subscribe.html', {'blogs': blogs, 'form': form})

templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>{% block title %}Информаг{% endblock title %}</title>
    <script type="text/javascript" src="{% static "jquery-3.3.1.min.js" %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link type="text/css" href="{% static "base.css" %}" rel="stylesheet">
</head>
<body>

{% block header %}
    <header>
        <div class="container-fluid" style="margin-bottom: 20px">
            <div class="col-12" align="center">
                <nav class="navbar navbar-expand-sm bg-light justify-content-center">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'index' %}">Лента новостей</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:blog' %}">Блог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Выход</a>
                        </li>
                    </ul>
                </nav>
                <br>
            </div>
        </div>
    </header>
{% endblock header %}

<main>
    <section>
        <div class="container">
            <div class="row justify-content-md-center">
                {% block content %}

                {% endblock content %}
            </div>
        </div>
    </section>
</main>


<footer>
    <div class="container-fluid">
        {% block footer %}
            <footer>
                <div class="content container-fluid">
                    <div class="row">
                        <div class="col-12 border" align="center">
                            <p>Подвал страницы</p>
                            <p>© Разработчик проекта - Донцов Е.Н.</p>
                        </div>
                    </div>
                </div>
            </footer>
        {% endblock footer %}
    </div>
</footer>

</body>
</html>

templates/blog/main.html
{% extends 'base.html' %}
{% block title %}Страница работы с блогом{% endblock %}
{% block header_page %}
    <br>
    <h3>
        <span class="header">Страница работы с блогом</span>
    </h3>
{% endblock header_page %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-xs-12" align="center">
                <hr>
                <h5>Список публикаций автора</h5><br>
                <table class="table table-hover table-bordered">
                    <thead>
                    <tr>
                        <th width="10">№пп</th>
                        <th width="70%" style="text-align: center">Название</th>
                        <th style="text-align: center">Редактировать</th>
                        <th style="text-align: center">Удалить</th>
                    </tr>
                    </thead>
                    {% if post_list %}
                        {% for post in post_list %}
                            <tbody>
                            <tr>
                                <th>{{ forloop.counter }}</th>
                                <td>
                                    <a class="nav-link"
                                       href="{% url 'blog:detail' post.id %}">
                                        {{ post.title }}
                                    </a></td>
                                <td align="center"><a class="nav-link"
                                                      href="{% url 'blog:update' post.id %}">
                                    Редактировать
                                    <span class="glyphicon glyphicon-edit"></span>
                                </a>
                                </td>
                                <td align="center">
                                    <a class="nav-link" href="{% url 'blog:delete' post.id %}">
                                        Удалить
                                        <span class="glyphicon glyphicon-remove" style="color: red"></span>
                                    </a>
                                </td>

                            </tr>
                            </tbody>
                        {% endfor %}
                    {% endif %}
                </table>
                <a class="nav-link" href="{% url 'blog:add' %}">Добавить публикацию</a>
                <br>
            </div>
            <hr>
        </div>
    </div>
    <div class="panel-footer">
        <p align="center"><a href="javascript:history.go(-1)">Назад</a></p>
    </div>
    <br>
{% endblock content %}

templates/blog/post.html
{% extends 'base.html' %}

{% block title %} {{ object.title }} {% endblock %}

{% block content %}
    <div class="col-xs-12 rules" align="justify">
        <h5 class="text-effect" itemprop="title"> {{ object.title }}</h5>
        <br>
        <p> {{ object.content }}</p>
        <p align="center"><a href="javascript:history.go(-1)">Назад</a></p>
    </div>
{% endblock %}

templates/blog/post_add.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Добавление публикации{% endblock %}

{% block content %}
    <div class="col-xs-12" align="center">
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Добавить"/>
        </form>
        <br>
        <a href="javascript:history.go(-1)" title="Назад">Назад</a>
    </div>
{% endblock %}

templates/blog/post_delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Удаление публикации{% endblock %}

{% block content %}
    <div class="col-xs-12" align="center">
        <a href="javascript:history.go(-1)" title="Назад">Назад</a>
        <br>
        <br>
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-danger">Вы действительно хотите удалить публикацию "{{ object }}"?</button>
        </form>
    <br>
    </div>

{% endblock %}

templates/blog/post_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Редактирование публикации{% endblock %}

{% block content %}
    <div class="col-xs-12" align="center">
        <div class="page-header">
            <h5> {{ object.title }} </h5>
        </div>
        <div>
            {% if object.blog.owner == user %}
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Обновить"/>
                </form>
            {% endif %}
        </div>
        <br>
        <div align="center">
            <a href="javascript:history.go(-1)" title="Назад">Назад</a>
        </div>
    </div>
{% endblock %}

templates/blog/subscribe.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Управление подписками{% endblock %}

{% block content %}
    <div class="col-xs-12" align="center">
        <div>
{#            {% if object.owner == user %}#}
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" value="Обновить"/>
                </form>
{#            {% endif %}#}
        </div>
        <br>
        <div align="center">
            <a href="javascript:history.go(-1)" title="Назад">Назад</a>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Персональная страница{% endblock %}

{% block content %}
    <div class="col-9" style="border: 5px">
        <div class="card">
            {% if news %}
                {% for post in news %}
                    <div class="" style="margin-bottom: 1px;">
                        <div class="card-header" style="margin-top: 1px">
                            <div>{{ post.posted }} <i>({{ post.blog }})</i></div>
                        </div>
                        <div class="content-title text-center">
                            <br>
                            <b><a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a></b>
                        </div>
                        <div class="" style="padding-bottom: 10px;padding-top: 3px;">
                            <div class="text-justify mx-4">
                                <p {% if user in post.readed_user.all %} style="color: #cecdc9;"
                                {% endif %}>
                                    {{ post.content }}</p>
                            </div>
                        </div>
                        <div align="center" class="my-2">
                            <a href="{% url 'blog:readed' post.id %}">
                                <small>Прочитан</small>
                            </a>
                        </div>

                    </div>
                {% endfor %}

                <nav>
                    <ul class="pagination justify-content-center">
                        {% if news.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{ news.previous_page_number }}">Предыдущая</a>
                            </li>
                        {% endif %}
                        <li class="page-item"><a class="page-link" href="?page=1">1</a></li>
                        {% if news.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{ news.next_page_number }}">Следующая</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>

            {% endif %}
        </div>
    </div>
    <div class="col-3" style="border: 1px">
        <div class="panel panel-default">
            <div class="card-header text-primary">Управление подписками</div>
            <div class="card">
                Текущие подписки:
                {% if blogs %}
                    <ul>
                        {% for blog in blogs %}
                            <li>{{ blog.title }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <a class="nav-link" href="{% url 'blog:subscribe' user.id %}">Изменить подписки</a>
            </div>
        </div>
    </div>


{% endblock content %}